
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myDb
{

using System;
    using System.Collections.Generic;
    
public partial class Chauffeur
{

    public int Id_chauf { get; set; }

    public string ref_chauf { get; set; }

    public string nom_chauf { get; set; }

    public string prenom { get; set; }

    public int nj_repos { get; set; }

    public bool disponibilite_chauf { get; set; }

}

}
