
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myDb
{

using System;
    using System.Collections.Generic;
    
public partial class Commande
{

    public int Id_comm { get; set; }

    public string ref_comm { get; set; }

    public int quantite { get; set; }

    public string ref_mag { get; set; }

    public System.DateTime date_livraison { get; set; }

}

}
