
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myDb
{

using System;
    using System.Collections.Generic;
    
public partial class Historique
{

    public int Id { get; set; }

    public string ref_com { get; set; }

    public string nom_mag { get; set; }

    public string adresse { get; set; }

    public string region { get; set; }

    public int quantity { get; set; }

    public System.DateTime date_com { get; set; }

    public string ref_vehi { get; set; }

    public string ref_chauf { get; set; }

}

}
