
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myDb
{

using System;
    using System.Collections.Generic;
    
public partial class location
{

    public int Id_location { get; set; }

    public string ref_mag { get; set; }

    public Nullable<double> longitude { get; set; }

    public Nullable<double> latitude { get; set; }

    public Nullable<double> zoom { get; set; }

}

}
