//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDbEntities : DbContext
    {
        public myDbEntities()
            : base("name=myDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chauffeur> Chauffeurs { get; set; }
        public virtual DbSet<Commande> Commandes { get; set; }
        public virtual DbSet<Historique> Historiques { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<Magazine> Magazines { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
    }
}
