
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace myDb
{

using System;
    using System.Collections.Generic;
    
public partial class Vehicule
{

    public int Id_vehi { get; set; }

    public string ref_vehi { get; set; }

    public string matricule { get; set; }

    public int capacite { get; set; }

    public Nullable<bool> disponibilite { get; set; }

}

}
